# https://d2lang.com/tour/sequence-diagrams/
shape: sequence_diagram
user: {shape: person}
user.t -> browser.t: accesURL
browser.t -> serverAPP.t1: requeteHttp
browser.t <- serverAPP.t1: redirectHttpIDP
browser.t -> serverIDP.t1: requeteHttp
browser.t <- serverIDP.t1: mireHtml
user.t <- browser.t: dessineMire
user.t -> browser.t1 : credentials
browser.t1 -> serverIDP.t2: auth
serverIDP.t2 <- browser.t1: redirectHttpAPP
browser.t1 -> serverAPP.t2: requeteHttp-token
browser.t1 <- serverAPP.t2: reponseHtml
user.t <- browser.t1: dessineAPP


