@startuml sequence-idp-with-logo
!include my-sprites.puml
!include skinparams.puml

participant "<$user>\n User" as user
participant "<$g-chrome>\n Browser" as browser
participant "<$web-service>\n Web Service" as serverAPP
participant "<$idp-keycloak>\n IDP KC" as serverIDP

autonumber


activate user
user -> browser: accesURL
activate browser
browser -> serverAPP: requeteHttp
activate serverAPP
return redirectHttpIDP
browser -> serverIDP: requeteHttp
activate serverIDP
return mireHtml
return  dessineMire


user -> browser : credentials
activate browser
browser -> serverIDP: auth
activate serverIDP
return redirectHttpAPP
browser -> serverAPP: requeteHttp-token
activate serverAPP
return reponseHtml
return dessineAPP
@enduml