= Racine des pages de documentation

=== Logos

Téléchargement des logos vectoriels depuis les site :

- https://techicons.dev/icons/debian
- https://www.svgrepo.com/

Create and adapt with https://inkscape.org/



=== Outils


*  D2
*  PlantUML
*  DrawIO


== DrawIO

Free and Open source graphic interface, many compatibilities, confluence, IDE, ...
Prefer install desktop version : https://github.com/jgraph/drawio-desktop/releases

== PlantUML

Best tools today for UML and C4 diagrams
Use logo and make sprite for personalise graphics : https://plantuml.com/fr-dark/sprite
A good link of plantuml documentation for svg optimisation : https://vecta.io/nano
Si l'image vectorielle pose problème à plantUML c'est peut être que des balises SVG ne sont pas supportées.
Forcer une conversion depuis un format png vers une image vectorielle, en ligne ou via Inkscape permettra sans doute de contourner le prblème.
Exemple de site de conversion en ligne : https://png2svg.com/fr/

== D2

use plugin in VSCode and InteliJ Commnunity
Installation : https://github.com/terrastruct/d2/blob/master/docs/INSTALL.md